Add TypeScript typings
Kequc/knex-stringcase pull request #14
Opened 2019-07-14 15:21 UTC by eioo

2019-07-14 21:50 UTC, Kequc requested changes

2019-07-14 21:50 UTC, Kequc commented on index.d.ts
> +        dbStringcase?: StringCase | StringCase[];
The two parameters appStringcase and dbStringcase can also include functions.

2019-07-14 21:50 UTC, Kequc commented on index.d.ts
> +        'trimcase' | 'uppercase';
I'm not sure all of these possible stringcases will remain consistent, if the stringcase library adds more of them then I'd need to update my library.

2019-07-14 22:00 UTC, Kequc commented
In general I'm not happy with adding typescript definitions because it means at least one additional dependency that only serves typescript users. The utiliy of this change seems fairly inconsequential because this library is essentially just doing configuration.

What I mean is, that while I understand that it's nice to have thorough autocompletion. It isn't needed when it's only used the first time you implement knex-stringcase into your configuration. And even then only if you are using typescript.

Is there a way to have a much looser implementation that doesn't force dependencies?

2019-07-15 01:41 UTC, eioo commented
You're right. The implementation was pretty bulky because of the dependency, it was also depending on knex package itself. @types/knex seems to be unmaintained anyways.

I made `knexStringcase()` generic and added usage example for it in README.md, let me know what you think.

2019-07-15 08:23 UTC, Kequc commented
That's a lot better thank you. I believe parameters appStringcase and dbStringcase are still incorrect as it can be a string, or a function or an array of strings, or an array of functions, or a mix of both.

2019-07-15 08:43 UTC, eioo commented
That should do it. "Stringcase" and "StringcaseFn" probably could have better names but didn't came up with any. But hey, now it works! 👍

2019-08-23 23:50 UTC, Kequc commented
I've decided not to support typescript on this project it's unnecessary.

2021-09-04 01:13 UTC, shellscape commented
Having a contributor go through all of those steps just to decide at the very end that you're not going to accept their work is a really bad look. At the very least you should have given them a detailed apology in return for their time.

2021-09-08 21:15 UTC, Kequc commented
It has remained here for over a year why would the fork go away. How cordial do I need to be in order not to get hounded by Typescript users. I think I explained in quite a lot of detail why it is unnecessary.

You're trying to guilt me and if I'm completely honest you're baiting me, why is that a good look and now I cared for this merge request?

If this feature is updated to use the newest patch version I'll merge it.

2021-09-08 21:52 UTC, shellscape commented
Maybe something is lost in translation on this one - it doesn't appear that you receive critical feedback well. If you perceive criticism regarding contributors and your behavior towards them as guilting, baiting, etc then open source may not be for you. You don't have to agree with feedback, but to suggest something so dramatic as "baiting" is juvenile.

Regardless, I'm disengaging from this project.

2021-09-11 21:31 UTC, Kequc commented
Thank you for your critical feedback, which was to pamper people with pleasantries. It's ok if you call repository owners juvenile though.

2021-09-11 21:31 UTC, closed without merging

2025-07-14 10:09 UTC, acro5piano commented
I'm really glad to see the migration to TypeScript on `v1.5.0`. Nice work! Thank you @Kequc

2025-07-14 10:41 UTC, Kequc commented
I came to realize Typescript should basically just be everywhere. Node has recently realized this too now Typescript seems to be supported out of the box. Unfortunately there's issues here with the import that I was not able to fix, but I'm sure we'll figure it out in time.

Might be just a named export instead of a default export is the way to go with libraries like this. Thanks!